### ISSUE TITLE
à propos de la boîte de dialogue

### ISSUE THREAD

**Issue by fmkr-project** [antoinech2/Le-jeu-de-la-MP#11]
Pour la suite j'ai modifié en interne la BDD afin de mettre une chaîne qui ne rentre pas dans la boîte (Seigneeeeeeeeeeeeee).

1.
"Effacer" la boîte de dialogue n'efface pas le texte qui déborde (les eee)
2.
Passer vers la fin l'affichage d'une chaîne A plus longue que la chaîne B suivante empêche l'affichage de la chaîne B.
3.
Si du texte déborde lorsque la boîte de dialogue disparaît, il sera toujours là lorsqu'une nouvelle boîte est générée

https://user-images.githubusercontent.com/91734800/143718936-3e2d3286-d5c8-4ff3-bcad-2172a9898fd4.mov

.

**Comment by Adamme-le-codeur-fou** [comment]
ha ui mais tkt javais pas fini pour linstant c'est dégueu ce que j'ai fait

**Comment by fmkr-project** [comment]
1., 2., 3. résolus après test

4.
Du texte trop long ne rentre pas dans la boîte

![seigne](https://user-images.githubusercontent.com/91734800/144310200-b85fa068-d584-47e5-99d0-4e34a4539daf.PNG)

**Comment by fmkr-project** [comment]
En supposant qu'aucun mot de la base de données ne fera pas plus de 50 caractères, fermeture du bug

**Comment by antoinech2** [comment]
https://user-images.githubusercontent.com/42295406/145720284-ed6945a0-6d55-416b-9f2c-4727b2a7a28b.mp4

Une ligne s'affiche sur celle d'avant lorsque l'on appuie sur la barre espace **après** que la première ligne soir affiché mais avant que la deuxième le soit.
