### ISSUE TITLE
Retour à la ligne dans un dialogue

### ISSUE THREAD

**Issue by fmkr-project** [antoinech2/Le-jeu-de-la-MP#22]
Implémenter une sorte de \n ou \t pour afficher un dialogue sur plusieurs lignes.

**Comment by antoinech2** [comment]
On a quelque chose qui peut permettre de le faire presque tout seul, en adaptant un peu : 
https://stackoverflow.com/questions/32590131/pygame-blitting-text-with-an-escape-character-or-newline#:~:text=Here%20is%20the%20anwser%20I%20found%20and%20used%20in%20my%20code.%20This%20produces%20a%20text%20surface%20that%20can%20be%20used%20normally
