### ISSUE TITLE
Impossible d'ouvrir redimension

### ISSUE THREAD

**Issue by fmkr-project** [antoinech2/Le-jeu-de-la-MP#26]
```
Traceback (most recent call last):
  File "C:\Users\thayt\Documents\GitHub\prepa-simulator\src\main.py", line 9, in <module>
    import game
  File "C:\Users\thayt\Documents\GitHub\prepa-simulator\src\game.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Testé à la fois avec IDLE et VS Code.
Lors du pip install, cmd sort un warning "pas de module s'appelant yaml"

**Comment by antoinech2** [comment]
`pip install pyyaml`

**Comment by fmkr-project** [comment]
Les 2 compilateurs ne veulent toujours pas importer yaml même avec pyyaml (même erreur)

**Comment by fmkr-project** [comment]
https://user-images.githubusercontent.com/91734800/146089443-430fd3ff-348d-4147-9ad4-eb8be5e101cb.mp4

J'ai aussi essayé de redémarrer mon PC, mais rien

**Comment by antoinech2** [comment]
Tu as 2 versions de pythons installées, la 3.9 et la 3.10. Le module est bien installé en version 3.10, mais par défaut c'est le 3.9 qui est utilisé (on le voit sur la vidéo). Le plus simple est de désinstaller la version 3.9

**Comment by fmkr-project** [comment]
Merci pour la remarque ! Sinon c'est normal ça :
```
Traceback (most recent call last):
  File "C:\Users\thayt\Documents\GitHub\prepa-simulator\src\main.py", line 14, in <module>
    game = game.Game()
  File "C:\Users\thayt\Documents\GitHub\prepa-simulator\src\game.py", line 33, in __init__
    self.window_size = (window_config.get("size").get("width"), window_config.get("size").get("height"))
AttributeError: 'NoneType' object has no attribute 'get'

```
?
En sachant qu'on affecte à cette variable, dans la ligne précédente, une valeur issue de yaml...

**Comment by antoinech2** [comment]
Je n'ai pas eu le temps d'upload la dernière version fonctionnelle, je fais ça demain
